import React from 'react';
import {
  HISButton
} from 'components/HISButton';

function HISButtonDefault() {
  return (
    <>
      <table className="component-table">
        <thead>
          <tr>
            <th>State(상태)</th>
            <th>Default(기본)</th>
            <th>Over(마우스오버)<br />Focus(키보드탭)</th>
            <th>Click(마우스클릭)</th>
            <th>Disable(비활성화)</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th>Create(생성)</th>
            <td>
              <HISButton
                labelText="추가"
                state="create"
                size="small"
              />
            </td>
            <td>
              <HISButton
                labelText="추가"
                theme="focus"
                state="create"
                size="small"
              />
            </td>
            <td>
              <HISButton
                labelText="추가"
                theme="click"
                state="create"
                size="small"
              />
            </td>
            <td>
              <HISButton
                labelText="추가"
                size="small"
                disabled
              />
            </td>
          </tr>
          <tr>
            <th>Read(읽기)</th>
            <td>
              <HISButton
                labelText="조회"
                state="read"
                size="small"
              />
            </td>
            <td>
              <HISButton
                labelText="조회"
                theme="focus"
                state="read"
                size="small"
              />
            </td>
            <td>
              <HISButton
                labelText="조회"
                theme="click"
                state="read"
                size="small"
              />
            </td>
            <td>
              <HISButton
                labelText="조회"
                size="small"
                disabled
              />
            </td>
          </tr>
          <tr>
            <th>Update(갱신)</th>
            <td>
              <HISButton
                labelText="저장"
                state="update"
                size="small"
              />
            </td>
            <td>
              <HISButton
                labelText="저장"
                theme="focus"
                state="update"
                size="small"
              />
            </td>
            <td>
              <HISButton
                labelText="저장"
                theme="click"
                state="update"
                size="small"
              />
            </td>
            <td>
              <HISButton
                labelText="저장"
                size="small"
                disabled
              />
            </td>
          </tr>
          <tr>
            <th>Delete(삭제)</th>
            <td>
              <HISButton
                labelText="삭제"
                state="delete"
                size="small"
              />
            </td>
            <td>
              <HISButton
                labelText="삭제"
                theme="focus"
                state="delete"
                size="small"
              />
            </td>
            <td>
              <HISButton
                labelText="삭제"
                theme="click"
                state="delete"
                size="small"
              />
            </td>
            <td>
              <HISButton
                labelText="삭제"
                size="small"
                disabled
              />
            </td>
          </tr>
        </tbody>
      </table>
    </>
  )
}

export default HISButtonDefault